{
  "props": [],
  "components": {
    "configFile": {
      "type": "script\\FileScript",
      "x": 128,
      "y": 16,
      "props": {
        "path": "browser.bin",
        "watch": "1"
      }
    },
    "jdownloader": {
      "type": "bundle\\jurl\\jURLDownloader",
      "x": 368,
      "y": 16,
      "props": []
    },
    "cfg": {
      "type": "script\\storage\\IniStorage",
      "x": 16,
      "y": 16,
      "props": {
        "path": "browser.bin",
        "autoSave": true,
        "multiLineValues": "1"
      }
    }
  }
}